
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-order
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test@123
    ports:
      - "5432:5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    networks:
      - order-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-order
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - order-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      timeout: 20s
      retries: 10

volumes:
  postgres-order-data:

networks:
  order-network:
    driver: bridge