# -------------------- DATABASE --------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=Test@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# -------------------- SERVER --------------------
server.port=8083
spring.application.name=PAYMENT-MICROSERVICE
spring.cloud.compatibility-verifier.enabled=false

# -------------------- EUREKA CLIENT --------------------
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.instance.hostname=localhost
eureka.client.service-url.default-zone=http://eureka-server:8761/eureka

# -------------------- RABBITMQ --------------------
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# NEW: Cancelled/Rollback keys
rabbitmq.queue.order-cancelled=order.cancelled.queue
rabbitmq.order.routing.cancelled=order.cancelled

# 1. Listening to Product Service
rabbitmq.queue.stock-deducted=stock-deducted-queue

rabbitmq.order.exchange=order.exchange

rabbitmq.queue.payment-success=payment.success.queue
rabbitmq.order.routing.success=payment.success

# Routing key for stock deducted events from Product Service
rabbitmq.product.routing.deducted=stock.deducted